runtime: python311
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

instance_class: F1

env_variables:
  DATABASE_URL: "postgresql://postgres.aicigvygzdsrjmkrkjez:oe8wVYmkvjJGHkET@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"

handlers:
- url: /.*
  script: auto
